# Generated by Django 4.2.5 on 2023-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contra',
            field=models.BinaryField(),
        ),
    ]
