# Generated by Django 4.2.5 on 2023-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AliasM', models.CharField(max_length=20)),
                ('creditos', models.IntegerField()),
                ('NBA', models.IntegerField()),
            ],
        ),
    ]
