# Generated by Django 4.2.5 on 2023-09-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userdata_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='creditos',
        ),
        migrations.AddField(
            model_name='userdata',
            name='CA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='CR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='NBA',
            field=models.IntegerField(default=0),
        ),
    ]
