# Generated by Django 4.2.5 on 2023-10-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userdata_creditos_userdata_ca_userdata_cr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='AliasM',
        ),
        migrations.AddField(
            model_name='userdata',
            name='PetInfo',
            field=models.JSONField(default={}),
        ),
    ]
