# Generated by Django 4.2.5 on 2023-10-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userdata_aliasm_userdata_petinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='PetInfo',
            field=models.JSONField(default=dict),
        ),
    ]
