# Generated by Django 4.2.5 on 2023-10-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userdata_petinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.IntegerField(default=0)),
                ('img', models.CharField(default='/static/img/example/item.png', max_length=100)),
                ('tipo', models.CharField(default='CA', max_length=2)),
            ],
        ),
    ]
