# Generated by Django 4.2.5 on 2023-10-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Items',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
