# Generated by Django 4.2.5 on 2023-11-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userdata_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('seg', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Items',
            field=models.JSONField(default=dict, max_length=9999),
        ),
    ]
