# Generated by Django 4.2.5 on 2023-11-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_leaderboard_alter_userdata_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nba',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
