# Generated by Django 4.2.5 on 2023-11-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_item_nba'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='d3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='nba',
            field=models.IntegerField(default=0),
        ),
    ]
