# Generated by Django 4.2.5 on 2023-11-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_item_d3_userdata_tickets_alter_item_nba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='d3',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='Tickets',
        ),
    ]
